pipeline {
    agent any

    stages {

        stage('Clone') {
            steps {
                git 'https://github.com/subasinik-blip/aws-devops-project.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('app') {
                    sh 'npm install'
                }
            }
        }

        stage('Build') {
            steps {
                echo "Build stage completed"
            }
        }

        stage('Run Application') {
            steps {
                dir('app') {
                    sh 'nohup node server.js &'
                }
            }
        }
    }
}
